volumes:
  sb_data:

services:
  postgres:
    image: postgres
    container_name: produit_postgres
    restart: always
    ports:
      - '5456:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Ewen2025@
      POSTGRES_DB: produit

  adminer:
      image: adminer
      container_name: adminer_produit
      restart: always
      ports:
        - '8082:8080'

  produit-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: produit-service
    restart: always
    ports:
      - '8081:8080'
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/produit
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: Ewen2025@
    depends_on:
      - postgres
